pickaxes:
  DIAMOND_PICKAXE:
    minLevel: 130
    secondsToMine: 1.0D
    pickaxe-item:
      material: DIAMOND_PICKAXE
      name: <#00FFFF>&lDiamond Pickaxe
      lore:
        - '&7&oThe pickaxe of a professional'
        - '&7&oIt''s only made out of <#00FFFF>Diamond&7!'
        - ' '
        - <#00FFFF>&lInformation &8»
        - ' &f* <#00FFFF>Energy: &f{energy}&8/&f{maxEnergy} &7({decimalPercent}%)'
        - ' &f* <#00FFFF>Blocks Mined: &f{blocks_broken}'
        - ' '
        - <#00FFFF>&lEnchantments &8»
        - '{enchantments}'
  ruby_pickaxe:
    minLevel: 150
    secondsToMine: 0.5D
    pickaxe-item:
      material: ruby_pickaxe
      name: <#FF0000>&lRuby Pickaxe
      lore:
        - '&7&oThe best pickaxe in the game!'
        - '&7&oIt''s only made out of <#FF0000>Ruby&7!'
        - ' '
        - <#FF0000>&lInformation &8»
        - ' &f* <#FF0000>Energy: &f{energy}&8/&f{maxEnergy} &7({decimalPercent}%)'
        - ' &f* <#FF0000>Blocks Mined: &f{blocks_broken}'
        - ' '
        - <#FF0000>&lEnchantments &8»
        - '{enchantments}'
test: "<#FF0000>&lEnchantments &8»"