name: KamiCommon
version: ${project.version}
main: com.kamikazejam.kamicommon.KamiCommon
authors: [ KamikazeJAM ]
softdepend:
  - PlaceholderAPI
  - ItemsAdder
  - MythicMobs
  - Citizens
description: KamikazeJAM's common library for Spigot and Standalone projects.
api-version: 1.13