name: KamiCommon
version: ${version}
main: com.kamikazejam.kamicommon.KamiCommon
authors: [ KamikazeJAM ]
softdepend:
  - PlaceholderAPI
  - SuperVanish
  - PremiumVanish
  - WorldEdit
  - WorldGuard
  - FastAsyncWorldEdit
description: KamikazeJAM's common library for Spigot.
api-version: 1.13