name: Gradle Build (on PR)

on:
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write # Access to Publish a Release
      packages: write # Access to Publish a Package

    #------------------------------------------------------------------------#
    #           Build the Artifact to test PR changes before merge           #
    #------------------------------------------------------------------------#
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Configure: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
      with:
        gradle-version: '9.0.0'

    - name: Build with Gradle (1.8.8)
      run: gradle build
      env:
        LUXIOUS_NEXUS_USER: ${{ secrets.MAVEN_NAME }}
        LUXIOUS_NEXUS_PASS: ${{ secrets.MAVEN_SECRET }}
        MC_SERVER_NEWEST_API: "false"

    - name: Build with Gradle (Latest Paper 1.21+)
      run: gradle build
      env:
        LUXIOUS_NEXUS_USER: ${{ secrets.MAVEN_NAME }}
        LUXIOUS_NEXUS_PASS: ${{ secrets.MAVEN_SECRET }}
        MC_SERVER_NEWEST_API: "true"