# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
  
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }}
  
    - name: Nexus Repository Publisher for GitHub Actions
      uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
      with:
        serverUrl: https://nexus.jartexsys.net/
        username: KamikazeJAM_YT
        password: ${{ secrets.NEXUS_PASS }}
        format: maven2
        repository: jartexsys-snapshots
        coordinates: groupId=com.kamikazejamplugins artifactId=kamicommon version=${{ steps.project.outputs.version }}
        assets: extension=jar
        filename: ./target/kamicommon-${{ steps.project.outputs.version }}.jar

