name: Maven Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Maven Settings
      uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: |
          [{
            "id": "luxious-public",
            "username": "${{ secrets.MAVEN_NAME }}",
            "password": "${{ secrets.MAVEN_SECRET }}"
          },{
            "id": "all-spigot-nms",
            "username": "jake-moore",
            "password": "${{ secrets.MY_TOKEN }}"
          }]

    - name: Display Settings.xml
      run: cat $GITHUB_WORKSPACE/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml

    - name: Display Settings.xml
      run: cat $GITHUB_WORKSPACE/settings.xml

    - name: Publish to Luxious Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      
